apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: presync-job
          image: ubuntu     
          command: 
            - /bin/bash
            - -c
            - |
              echo "This is pre-sync"
      restartPolicy: Never
