apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation    
spec:
  template:
    spec:
      containers:
        - name: presync-job
          image: ubuntu
          imagePullPolicy: IfNotPresent
          command: 
            - /bin/bash
            - -c
            - |
              echo "This is pre-sync"
              echo "Changed hook again"
      restartPolicy: Never
